nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_headers: ['Content-Type', 'X-MAILER-KEY']
        allow_methods: ['POST']
        max_age: 3600
    paths:
        '^/': ~
