security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_memory:
            memory:
                users:
                    api_user:
                        password: null
                        roles: ['ROLE_API']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            stateless: true
            provider: users_in_memory
            custom_authenticators:
                - App\Security\ApiAuthenticator
            # lazy: true → inutile ici si tu es en stateless

    access_control:
        - { path: ^/, roles: ROLE_API }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
